server:
  port: 24936

spring.batch.job.names: ${job.name:NONE}

spring:
  application:
    name: batch
  profiles: mariadb
  datasource:
    username: keta
    password: keta!234
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://121.78.118.213:13306/keta?autoReconnect=true
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql : true
logging:
  level:
    org:
      hiberante:
        type:
          descriptor:
            sql: trace
mybatis:
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
  config-location: classpath:mappers/mybatis-config.xml
  mapper-locations: classpath*:mappers/*.xml
  executorType: BATCH
